name: Keep Active

on:
  schedule:
    - cron: "0 0 */5 * *"  # æ¯15å¤©è¿è¡Œä¸€æ¬¡
  workflow_dispatch:

env:
  PAT: ${{ secrets.PAT }}
  USER: ${{ secrets.USER }}
  REPO: ${{ secrets.REPO }}

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install jinja2 python-dotenv

    - name: Run bludweb.py to generate 'webs' directory
      run: python templates/bludweb.py webs 6
      env:
        PAT: ${{ secrets.PAT }}
        USER: ${{ secrets.USER }}
        REPO: ${{ secrets.REPO }}

    - name: Set Git user identity
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Check for uncommitted changes and commit
      run: |
        # æ£€æŸ¥æ˜¯å¦æœ‰æœªæäº¤çš„æ›´æ”¹
        git diff --exit-code || (
          git add .
          git commit -m "ğŸš€ Auto-commit untracked changes before pulling"
        )

    - name: Pull and rebase remote changes
      run: |
        git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USER }}/${{ secrets.REPO }}.git
        git pull --rebase origin main

    - name: Push changes to remote repository
      run: |
        git add webs
        git commit -m "ğŸš€ Update webs/ folder by GitHub Actions on $(date +'%F %T')"
        git push origin main
      env:
        TOKEN: ${{ secrets.PAT }}
